site_name: Central Operations Platform
theme: material
use_directory_urls: false
nav:
  - Home: index.md
  - Organisation: organisation.md
  - Business Management: business-management.md
  - Product Management: product-management.md
  - Product Engineering: product-engineering.md
  - Core Platform: core-platform.md
  - Developer Onboarding: developer-onboarding.md
  - Live Services: live-services.md

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 3
  - markdown_include.include
