site_name: Central Operations Platform
theme: material
use_directory_urls: false
nav:
  - Home: index.md

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 3
  - markdown_include.include
